const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.Mouse,
		C3.Behaviors.Timer,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnEnd,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop
	];
};
self.C3_JsPropNameTable = [
	{LiteTween: 0},
	{judul_game: 0},
	{background: 0},
	{papan1: 0},
	{dokter_k: 0},
	{button_1: 0},
	{button_2: 0},
	{button_3: 0},
	{button_4: 0},
	{Mouse: 0},
	{Timer: 0},
	{BGM: 0},
	{tutup: 0},
	{button_musik_play: 0},
	{Touch: 0},
	{Audio: 0},
	{Browser: 0},
	{background_mengenal: 0},
	{pict_gigi_geraham: 0},
	{button_home: 0},
	{button_previous: 0},
	{button_next: 0},
	{pict_gigi_seri: 0},
	{papan_2: 0},
	{jenis_gigi: 0},
	{papan_3: 0},
	{text_gigi: 0},
	{papan_soal: 0},
	{pita: 0},
	{textSoal: 0},
	{layout_jawaban: 0},
	{pict_gigi_taring: 0},
	{pick_gigi_premolar: 0},
	{pick_gigi_ompong: 0},
	{papanSkor: 0},
	{text_skor: 0},
	{back_quiz: 0},
	{anatomiGigi: 0},
	{papanEdukasi: 0},
	{obatKumurGigi: 0},
	{benangGigi: 0},
	{sikatGigi: 0},
	{makananAsam: 0},
	{makanEsKrim: 0},
	{dampakMinumSoda: 0},
	{soda: 0},
	{gigirusak2: 0},
	{dokterperiksa: 0},
	{periksagigi: 0},
	{Pelindung: 0},
	{helm: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{textEdukasi: 0},
	{anatomi_mulut2: 0},
	{Skor: 0},
	{Skor2: 0},
	{Skor3: 0},
	{Skor4: 0},
	{Skor5: 0}
];

self.InstanceType = {
	judul_game: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	papan1: class extends self.ISpriteInstance {},
	dokter_k: class extends self.ISpriteInstance {},
	button_1: class extends self.ISpriteInstance {},
	button_2: class extends self.ISpriteInstance {},
	button_3: class extends self.ISpriteInstance {},
	button_4: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	BGM: class extends self.ISpriteInstance {},
	tutup: class extends self.ISpriteInstance {},
	button_musik_play: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	background_mengenal: class extends self.ISpriteInstance {},
	pict_gigi_geraham: class extends self.ISpriteInstance {},
	button_home: class extends self.ISpriteInstance {},
	button_previous: class extends self.ISpriteInstance {},
	button_next: class extends self.ISpriteInstance {},
	pict_gigi_seri: class extends self.ISpriteInstance {},
	papan_2: class extends self.ISpriteInstance {},
	jenis_gigi: class extends self.ISpriteInstance {},
	papan_3: class extends self.ISpriteInstance {},
	text_gigi: class extends self.ITextInstance {},
	papan_soal: class extends self.ISpriteInstance {},
	pita: class extends self.ISpriteInstance {},
	textSoal: class extends self.ITextInstance {},
	layout_jawaban: class extends self.ISpriteInstance {},
	pict_gigi_taring: class extends self.ISpriteInstance {},
	pick_gigi_premolar: class extends self.ISpriteInstance {},
	pick_gigi_ompong: class extends self.ISpriteInstance {},
	papanSkor: class extends self.ISpriteInstance {},
	text_skor: class extends self.ITextInstance {},
	back_quiz: class extends self.ISpriteInstance {},
	anatomiGigi: class extends self.ISpriteInstance {},
	papanEdukasi: class extends self.ISpriteInstance {},
	obatKumurGigi: class extends self.ISpriteInstance {},
	benangGigi: class extends self.ISpriteInstance {},
	sikatGigi: class extends self.ISpriteInstance {},
	makananAsam: class extends self.ISpriteInstance {},
	makanEsKrim: class extends self.ISpriteInstance {},
	dampakMinumSoda: class extends self.ISpriteInstance {},
	soda: class extends self.ISpriteInstance {},
	gigirusak2: class extends self.ISpriteInstance {},
	dokterperiksa: class extends self.ISpriteInstance {},
	periksagigi: class extends self.ISpriteInstance {},
	Pelindung: class extends self.ISpriteInstance {},
	helm: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	textEdukasi: class extends self.ITextInstance {},
	anatomi_mulut2: class extends self.ISpriteInstance {}
}